SELECT C_CUSTKEY, C_NAME, SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS REVENUE, C_ACCTBAL, N_NAME, C_ADDRESS, C_PHONE, C_COMMENT
FROM LINEITEM JOIN ORDERS ON L_ORDERKEY = O_ORDERKEY
    JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
    JOIN NATION ON C_NATIONKEY = N_NATIONKEY
WHERE O_ORDERDATE >= DATE '1994-11-01' AND O_ORDERDATE < DATE '1995-02-01' AND  L_RETURNFLAG = 'R' 
GROUP BY C_CUSTKEY, C_NAME, C_ACCTBAL, C_PHONE, N_NAME, C_ADDRESS, C_COMMENT
ORDER BY REVENUE DESC
LIMIT 20
