SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE FROM
SUPPLIER JOIN 
(SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE*(1.0-L_DISCOUNT)) AS TOTAL_REVENUE
    FROM LINEITEM 
    WHERE L_SHIPDATE >= DATE '1993-09-01' AND L_SHIPDATE < DATE '1993-12-01'
    GROUP BY L_SUPPKEY
) AS TMP_VIEW
ON S_SUPPKEY = L_SUPPKEY
ORDER BY TOTAL_REVENUE DESC
LIMIT 1
