SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(*) AS SUPPLIER_CNT
FROM
(
SELECT COUNT(*) AS CNT
FROM PART JOIN PARTSUPP ON P_PARTKEY = PS_PARTKEY
ANTI JOIN (
SELECT S_SUPPKEY
FROM SUPPLIER 
WHERE S_COMMENT LIKE '%%Customer%%Complaints%%'
) AS TMP_VIEW ON PS_SUPPKEY = S_SUPPKEY
WHERE P_BRAND != 'Brand#21'AND P_TYPE NOT LIKE 'PROMO PLATED%%' AND
(P_SIZE = 23 OR P_SIZE = 3 OR P_SIZE = 33 OR P_SIZE = 29 OR
 P_SIZE = 40 OR P_SIZE = 27 OR P_SIZE = 22 OR P_SIZE = 4)
GROUP BY P_BRAND, P_TYPE, P_SIZE, PS_SUPPKEY
) AS TMP_VIEW
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE
