SELECT  C_NAME, C_CUSTKEY, O_ORDERKEY, O_ORDERDATE, O_TOTALPRICE, SUM(SUM_L_QUANTITY) AS TOTAL_L_QUANTITY
FROM ORDERS JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
JOIN (
    SELECT L_ORDERKEY AS SUM_L_ORDERKEY, SUM(L_QUANTITY) AS SUM_L_QUANTITY FROM LINEITEM GROUP BY L_ORDERKEY HAVING SUM_L_QUANTITY > 300
  ) AS TMP_VIEW
ON O_ORDERKEY = SUM_L_ORDERKEY
GROUP BY C_NAME, C_CUSTKEY, O_ORDERKEY, O_ORDERDATE, O_TOTALPRICE
ORDER BY O_TOTALPRICE DESC, O_ORDERDATE
