SELECT SUM(L_EXTENDEDPRICE* (1 - L_DISCOUNT)) AS REVENUE
FROM LINEITEM JOIN PART ON L_PARTKEY = P_PARTKEY
WHERE (P_BRAND = 'Brand#31' AND (P_CONTAINER = 'SM CASE' OR P_CONTAINER = 'SM BOX' OR P_CONTAINER = 'SM PACK' OR P_CONTAINER = 'SM PKG') AND L_QUANTITY >= 4 AND L_QUANTITY <= 14 AND P_SIZE<=5
  AND (L_SHIPMODE = 'AIR' OR L_SHIPMODE = 'AIR REG') AND L_SHIPINSTRUCT = 'DELIVER IN PERSON')
    OR (P_BRAND ='Brand#43' AND (P_CONTAINER = 'MED BAG' OR P_CONTAINER = 'MED BOX' OR P_CONTAINER = 'MED PKG' OR P_CONTAINER = 'MED PACK') AND L_QUANTITY >=15 AND L_QUANTITY <= 25 AND P_SIZE<=10 
  AND (L_SHIPMODE = 'AIR' OR L_SHIPMODE = 'AIR REG') AND L_SHIPINSTRUCT = 'DELIVER IN PERSON') 
    OR (P_BRAND = 'Brand#43' AND (P_CONTAINER = 'LG CASE' OR P_CONTAINER = 'LG BOX' OR P_CONTAINER = 'LG PACK' OR P_CONTAINER = 'LG PKG') AND L_QUANTITY >=26 AND L_QUANTITY <= 36 AND P_SIZE<=15
  AND (L_SHIPMODE = 'AIR' OR L_SHIPMODE = 'AIR REG') AND L_SHIPINSTRUCT = 'DELIVER IN PERSON')

