SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM SUPPLIER 
JOIN PARTSUPP ON S_SUPPKEY = PS_SUPPKEY
JOIN NATION ON S_NATIONKEY = N_NATIONKEY
JOIN PART ON PS_PARTKEY = P_PARTKEY
JOIN REGION ON N_REGIONKEY = R_REGIONKEY
JOIN 
(SELECT P_PARTKEY AS MIN_P_PARTKEY, MIN(PS_SUPPLYCOST) AS MIN_PS_SUPPLYCOST
FROM SUPPLIER 
JOIN PARTSUPP ON S_SUPPKEY = PS_SUPPKEY
JOIN NATION ON S_NATIONKEY = N_NATIONKEY
JOIN PART ON PS_PARTKEY = P_PARTKEY
JOIN REGION ON N_REGIONKEY = R_REGIONKEY
WHERE P_SIZE = 43 AND P_TYPE LIKE '%%TIN' AND R_NAME = 'AFRICA'
GROUP BY P_PARTKEY
) AS TMP_VIEW
ON P_PARTKEY = MIN_P_PARTKEY AND PS_SUPPLYCOST = MIN_PS_SUPPLYCOST
WHERE P_SIZE = 43 AND P_TYPE LIKE '%%TIN' AND R_NAME = 'AFRICA' 
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;
