SELECT S_NAME, S_ADDRESS FROM 
SUPPLIER JOIN NATION ON S_NATIONKEY = N_NATIONKEY
JOIN (
SELECT SUM(0.5 * L_QUANTITY) AS TOTAL_L_QUANTITY FROM 
PART JOIN PARTSUPP ON P_PARTKEY = PS_PARTKEY
JOIN LINEITEM ON PS_PARTKEY = L_PARTKEY AND PS_SUPPKEY = L_SUPPKEY
WHERE L_SHIPDATE >= DATE '1996-01-01' AND L_SHIPDATE < DATE '1997-01-01' AND P_NAME LIKE 'azure%%'
GROUP BY PS_PARTKEY, PS_SUPPKEY, PS_AVAILQTY
HAVING PS_AVAILQTY > TOTAL_L_QUANTITY
) AS TMP_VIEW 
ON S_SUPPKEY = PS_SUPPKEY
WHERE N_NAME = 'JORDAN'
ORDER BY S_NAME
