SELECT SUBSTRING(C_PHONE,1,2) AS CNTRYCODE, COUNT(*) AS TOTAL, SUM(C_ACCTBAL) AS TOTACCTBAL
FROM
(
SELECT C_PHONE, C_ACCTBAL
FROM CUSTOMER ANTI JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
WHERE (C_PHONE LIKE '23%%' OR 
    C_PHONE LIKE '29%%' OR C_PHONE LIKE '22%%' OR C_PHONE LIKE '20%%' OR
    C_PHONE LIKE '24%%' OR C_PHONE LIKE '26%%' OR C_PHONE LIKE '25%%')
HAVING C_ACCTBAL > (SELECT AVG(C_ACCTBAL) AS CNT
  FROM CUSTOMER
  WHERE C_ACCTBAL > 0.00 AND (C_PHONE LIKE '23%%' OR 
    C_PHONE LIKE '29%%' OR C_PHONE LIKE '22%%' OR C_PHONE LIKE '20%%' OR
    C_PHONE LIKE '24%%' OR C_PHONE LIKE '26%%' OR C_PHONE LIKE '25%%')
)) AS TMP_VIEW
GROUP BY CNTRYCODE
ORDER BY CNTRYCODE
