SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER 
    JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
    JOIN LINEITEM ON O_ORDERKEY = L_ORDERKEY
WHERE C_MKTSEGMENT = 'HOUSEHOLD' AND O_ORDERDATE < DATE '1995-03-04' AND L_SHIPDATE > DATE '1995-03-04'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10
