SELECT O_ORDERPRIORITY, COUNT(*) AS ORDER_COUNT 
FROM ORDERS LEFT SEMI JOIN LINEITEM ON O_ORDERKEY = L_ORDERKEY AND L_COMMITDATE < L_RECEIPTDATE
WHERE O_ORDERDATE >= DATE '1993-08-01' AND O_ORDERDATE < DATE '1993-11-01'
GROUP BY O_ORDERPRIORITY
ORDER BY O_ORDERPRIORITY
