SELECT N1.N_NAME, N2.N_NAME, YEAR(L_SHIPDATE) AS O_YEAR, SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS VOLUME
FROM NATION N1 JOIN NATION N2 ON 1 = 1
JOIN SUPPLIER ON N1.N_NATIONKEY = S_NATIONKEY
JOIN LINEITEM ON S_SUPPKEY = L_SUPPKEY
JOIN ORDERS ON L_ORDERKEY = O_ORDERKEY
JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY AND N2.N_NATIONKEY = C_NATIONKEY
WHERE ((N1.N_NAME = 'UNITED STATES' AND N2.N_NAME = 'INDONESIA') OR (N1.N_NAME = 'INDONESIA' AND N2.N_NAME = 'UNITED STATES')) AND
L_SHIPDATE >= DATE '1995-01-01' AND L_SHIPDATE <= DATE '1996-12-31'
GROUP BY N1.N_NAME, N2.N_NAME, O_YEAR
ORDER BY N1.N_NAME, N2.N_NAME, O_YEAR
