SELECT YEAR(O_ORDERDATE) AS O_YEAR, SUM(CASE WHEN N2.N_NAME = 'INDONESIA' THEN L_EXTENDEDPRICE*(1-L_DISCOUNT) ELSE 0.0 END ) / SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS MKT_SHARE
FROM NATION N1 JOIN NATION N2 ON 1 = 1
JOIN REGION ON N1.N_REGIONKEY = R_REGIONKEY
JOIN SUPPLIER ON N2.N_NATIONKEY = S_NATIONKEY
JOIN LINEITEM ON S_SUPPKEY = L_SUPPKEY
JOIN PART ON L_PARTKEY = P_PARTKEY
JOIN ORDERS ON L_ORDERKEY = O_ORDERKEY
JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY AND N1.N_NATIONKEY = C_NATIONKEY
WHERE R_NAME = 'ASIA' AND O_ORDERDATE >= DATE '1995-01-01' AND O_ORDERDATE < DATE '1996-12-31' AND P_TYPE = 'MEDIUM ANODIZED NICKEL'
GROUP BY O_YEAR
ORDER BY O_YEAR
